### ISSUE TITLE
Site refactoring

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#1]
All the site should now be served from Jekyll, and managed from a unique repository.

This work has already been started in mango-blog repository.

To do:
- [x] git repos management - merge site, blog and tools #2
- [ ] site improvements (structure)
  - [ ] upgrade to latest stable Jekyll
  - [ ] switch to Foundation #6
  - [ ] update blog structure: new categories, move existing articles accordingly
  - [ ] integrate blog CTAs per category
- [ ] site content
  - [ ] add a "general conditions" page #3
  - [ ] add landing page for social media offer
  - [ ] add landing page for business intelligence offer
  - [ ] add landing page for dataviz offer
- [ ] blog content
  - [ ] write, publish and promote articles

**Comment by mef** [comment]
replaced by #38
