### ISSUE TITLE
Decommission pullReceipt landing page

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#176]
Work on pullReceipt is suspended at the moment:

* not enough interest from the market has been measured (although not much marketing effort has been done)
* I don't have time to keep working on it.

**todo**

- [x] update landing page to reflect current status
- [ ] inform mailing list subscribers
- [x] communicate on pullReceipt's twitter account

To add in separate issues:
* blog article(s) about pullReceipt (prototype review, engineering...)
* open source current prototype
