### ISSUE TITLE
head meta tags

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#29]
update the layout template to complete the meta tags ( some are missing, like prevArticle link, robots noindex etc)

- [x] titles for the various type of pages, with support for subtitles
- [x] robots noindex/nofollow on non-prod environments
- [x] opengraph meta tags 
- [x] canonical
- [x] xml alternate
- [x] rel prev/next

Extra tags to be added if needed in a separate issue/release
