### ISSUE TITLE
Upgrade roadmap

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#38]
To do:

- [x] switch to hexo instead of jekyll
- [x] switch to a skeleton build instead of bootstrap
- [x] implement new visual identity
- [x] ~~update blog structure: new categories, move existing articles accordingly~~
- [x] ~~integrate blog CTAs per category~~
